% This script alters the header of a NIfTI file. It is based on
% \spm8\@nifti\Contents.m
%

% Guilherme C. Beltramini - 2011-Dec-06, 03:47 pm

[fname,fpath,filterindex] = uigetfile({'*.nii','NIfTI files (*.nii)'},...
    'Pick a NIfTI file','MultiSelect','off');
% Ex.: fname = Image_1.nii
% multiple selection only works for files in the same folder
% fname = cellstr(num2str(fname)); - for multiple selection
if isequal(fname,0)
    return
end

disp('-------------------------------------------------------------------')
fprintf('Running change_nifti_header.m...\n')

%fname_new = sprintf('%s_mod.nii',f_name(1:strfind(f_name,'.nii')-1));
fname_new = [fname(1:end-4) '_mod.nii'];
copyfile(fullfile(fpath,fname),fullfile(fpath,fname_new))

Ni = nifti(fullfile(fpath,fname_new)); % Get handle for existing file
N = Ni;% Base new handle on this

% Create figure with specific title
fig = figure;
set(fig,'MenuBar','none',...
    'ToolBar','none',...
    'Name','You may choose any of the attributes below to change:',...
    'NumberTitle','off')

% To avoid problems with the underscore character
set(0,'DefaulttextInterpreter','none')
% alternatives: use '\_' or set(handle,'interpreter','none')

% Print text
if isempty(N.timing)
    text(0,0.5,{...
        'N =',...
        '',...
        'NIFTI object: 1-by-1',...
        '             dat: [4-D file_array] (SEE BELOW)',...
        '            mat: [4x4 double]',...
        sprintf('  mat_intent: ''%s''',N.mat_intent),... %'mat_intent: ''Scanner'''
        '          mat0: [4x4 double]',...
        sprintf(' mat0_intent: ''%s''',N.mat0_intent),... %'mat0_intent: ''Scanner'''
        sprintf('       descrip: ''%s''',N.descrip),... %'descrip: ''Some description'''
        '',...
        ' N.dat',...
        '        fname: image file name  -  DO NOT CHANGE THIS!',... %sprintf('        fname: %s  -  DO NOT CHANGE THIS!',N.dat.fname),... % the name is too large
        sprintf('           dim: [%d %d %d %d]',N.dat.dim),... %'dim: [80 80 40 200]'
        sprintf('        dtype: ''%s''',N.dat.dtype),... %'dtype: ''INT16-LE'''
        sprintf('        offset: %d',N.dat.offset),... %'offset: 352'
        sprintf('  scl_slope: %.4f',N.dat.scl_slope),... %'scl_slope: 1'
        sprintf('    scl_inter: %.4f',N.dat.scl_inter),... %'scl_inter: 0'
        '',...
        sprintf('Write the change you want to make (e.g., "N.dat.dim = [%d %d %d %d]"):',N.dat.dim(1:3),N.dat.dim(4)-15) } )
        %'Write the change you want to make (e.g., "N.dat.dim = [80 80 40 98]"):'})
else
        text(0,0.5,{...
        'N =',...
        '',...
        'NIFTI object: 1-by-1',...
        '             dat: [4-D file_array] (SEE BELOW)',...
        '            mat: [4x4 double]',...
        sprintf('  mat_intent: ''%s''',N.mat_intent),...
        '          mat0: [4x4 double]',...
        sprintf(' mat0_intent: ''%s''',N.mat0_intent),...
        '         timing: [1x1 struct] (SEE BELOW)',...
        sprintf('       descrip: ''%s''',N.descrip),...
        '',...
        ' N.dat',...
        '        fname: image file name  -  DO NOT CHANGE THIS!',... %sprintf('        fname: %s  -  DO NOT CHANGE THIS!',N.dat.fname),...
        sprintf('           dim: [%d %d %d %d]',N.dat.dim),...
        sprintf('        dtype: ''%s''',N.dat.dtype),...
        sprintf('        offset: %d',N.dat.offset),...
        sprintf('  scl_slope: %.4f',N.dat.scl_slope),...
        sprintf('    scl_inter: %.4f',N.dat.scl_inter),...
        '',...
        ' N.timing',...
        sprintf('      toffset: %d',N.timing.toffset),...
        sprintf('     tspace: %d',N.timing.tspace),...
        '',...
        sprintf('Write the change you want to make (e.g., "N.dat.dim = [%d %d %d %d]"):',N.dat.dim(1:3),N.dat.dim(4)-15) } );
end

set(gca,'Visible','off')

com = uicontrol('Style','edit',...
    'String','N.dat.dim = ',...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left',...
    'Position',[75 50 200 20]);

button = uicontrol('Position',[300 50 70 20],...
    'String','OK',...
    'Callback','uiresume(gcbf)');

screen_res = get(0,'ScreenSize'); % screen resolution
screen_res = screen_res(3:4);
w_size = [560*screen_res(1)/1920 544*screen_res(2)/1080]; % window size

%set(fig,'Position',[(screen_res(1)-w_size(1))/2 (screen_res(2)-w_size(2))/2 ...
%    w_size])
set(fig,'Position',[(screen_res(1)-w_size(1))/2 (screen_res(2)-w_size(2))/2 ...
    560 544])
uiwait(fig);

try
    eval(get(com,'String'));
    close(fig);
    create(N); % Write new header

% It seems that if any value is given to the variable 'dat', it will be
% written in the image with the header above.

    fprintf('change_nifti_header.m done!\n')
    fprintf('New image %s was created\n',fullfile(fpath,fname_new))
    disp('-------------------------------------------------------------------')
catch
    delete(fullfile(fpath,fname_new))
    disp('Nothing was done')
    disp('-------------------------------------------------------------------')
end

% Set back the default value
set(0,'DefaulttextInterpreter','tex')